resources:
  - url: /local/mini-media-player-bundle.js?v=1.0.3
    type: module
  - url: /local/light-entity-card.js?track=true
    type: js
  - url: /local/simple-weather-card.bundle.js?v=0.3.0
    type: module

title: Home Control
views:
  - title: Lights
    cards:
      - type: custom:light-entity-card 
        entity: light.entertainment_room
      - type: custom:light-entity-card 
        entity: light.hue_color_lamp_5
      - type: custom:light-entity-card 
        entity: light.hue_color_lamp_6 
      - type: custom:light-entity-card 
        entity: light.hue_color_lamp_1_2 
  - title: Speakers
    cards:
      - type: "custom:mini-media-player" 
        entity: media_player.bedroom_speaker
      - type: "custom:mini-media-player" 
        entity: media_player.googlehome9786
      - type: "custom:mini-media-player" 
        entity: media_player.kitchen_speaker
      - type: "custom:mini-media-player" 
        entity: media_player.spotify
  - title: Sensors
    cards:
      - type: entities
        title: Ring Doorbell
        show_header_toggle: false
        entities:
          - binary_sensor.ring_front_door_ding
          - binary_sensor.ring_front_door_motion
          - sensor.ring_front_door_last_ding
          - sensor.ring_front_door_last_motion
      - type: weather-forecast
        entity: weather.dark_sky 
      - type: entities
        entities:
          - sensor.speedtest_ping
          - sensor.speedtest_download
          - sensor.speedtest_upload
      - type: entities
        entities:
          - sensor.stairway_lux
          - sensor.stairway_temperature
          - sensor.office_lux
          - sensor.office_temperature
  - title: Front Door
    cards:
      - type: picture-glance
        title: Front Door
        entities:
          - binary_sensor.ring_front_door_motion
          - binary_sensor.ring_front_door_ding
        camera_image: camera.front_door
      - type: entities
        entities:
          - binary_sensor.ring_front_door_ding
          - binary_sensor.ring_front_door_motion
          - sensor.ring_front_door_last_activity
          - sensor.ring_front_door_last_ding
          - sensor.ring_front_door_last_motion
          - sensor.ring_front_door_volume
          - sensor.ring_front_door_wifi_signal_category
          - sensor.ring_front_door_wifi_signal_strength
      - type: custom:light-entity-card 
        entity: light.hue_color_lamp_1_2 
      
